### ISSUE TITLE
Feature: Add ability to log only specific messages

### ISSUE THREAD

**Issue by guydelta** [mongoose-os-libs/file-logger#1]
Right now all mongoose events gets logged to file, which fills the filesystem quite quickly or can fill the logs with unwanted information. It will be nice if a feature is added by which custom handlers can be added, e.g. only if I call file_logger.log(message) from init.js will that message be posted to the file-logger log.

**Comment by cpq** [comment]
See https://github.com/cesanta/mongoose-os/blob/master/fw/src/mgos_sys_config.yaml#L20
